/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

/**
 *
 * @author marii
 */
public class VistaMenuPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VistaMenuPrincipal.class.getName());

    /**
     * Creates new form VistaMenuPrincipal
     */
    public VistaMenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pnlEncabezado = new javax.swing.JPanel();
        lblStorageBox = new javax.swing.JLabel();
        lblSubtitulo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblTitulo = new javax.swing.JLabel();
        lblDescripcion = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pnlEspacios = new javax.swing.JPanel();
        lblEspacios = new javax.swing.JLabel();
        lblImagenEspacios = new javax.swing.JLabel();
        btnEspacios = new javax.swing.JButton();
        pnlClientes = new javax.swing.JPanel();
        lblClientes = new javax.swing.JLabel();
        lblImagenClientes = new javax.swing.JLabel();
        btnClientes = new javax.swing.JButton();
        pnlServicios = new javax.swing.JPanel();
        lblServicios = new javax.swing.JLabel();
        lblImagenServicios = new javax.swing.JLabel();
        btnServicios = new javax.swing.JButton();
        pnlEmpleados = new javax.swing.JPanel();
        lblEmpleados = new javax.swing.JLabel();
        lblImagenEmpleados = new javax.swing.JLabel();
        btnEmpleados = new javax.swing.JButton();
        pnlContratos = new javax.swing.JPanel();
        lblContratos = new javax.swing.JLabel();
        lblImagenContratos = new javax.swing.JLabel();
        btnContratos = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("StorageBox - Menú Principal");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        pnlEncabezado.setBackground(new java.awt.Color(42, 99, 153));
        pnlEncabezado.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        pnlEncabezado.setForeground(new java.awt.Color(42, 99, 153));

        lblStorageBox.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        lblStorageBox.setForeground(new java.awt.Color(255, 255, 255));
        lblStorageBox.setText("StorageBox");

        lblSubtitulo.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        lblSubtitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblSubtitulo.setText("Sistema de Alquiler de Espacios");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/archive-48.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        lblTitulo.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setText("Menú Principal");

        lblDescripcion.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        lblDescripcion.setForeground(new java.awt.Color(255, 255, 255));
        lblDescripcion.setText("Seleccione una opción para acceder a las funcionalidades del sistema.");

        javax.swing.GroupLayout pnlEncabezadoLayout = new javax.swing.GroupLayout(pnlEncabezado);
        pnlEncabezado.setLayout(pnlEncabezadoLayout);
        pnlEncabezadoLayout.setHorizontalGroup(
            pnlEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEncabezadoLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblStorageBox)
                    .addComponent(lblSubtitulo))
                .addGap(26, 26, 26)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitulo)
                    .addComponent(lblDescripcion))
                .addContainerGap(119, Short.MAX_VALUE))
        );
        pnlEncabezadoLayout.setVerticalGroup(
            pnlEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEncabezadoLayout.createSequentialGroup()
                .addGroup(pnlEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlEncabezadoLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jSeparator1))
                    .addGroup(pnlEncabezadoLayout.createSequentialGroup()
                        .addGroup(pnlEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlEncabezadoLayout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(lblTitulo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblDescripcion))
                            .addGroup(pnlEncabezadoLayout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(pnlEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1)
                                    .addGroup(pnlEncabezadoLayout.createSequentialGroup()
                                        .addComponent(lblStorageBox)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblSubtitulo)))))
                        .addGap(0, 13, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(42, 99, 153));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("MÓDULOS DEL SISTEMA");

        pnlEspacios.setBackground(new java.awt.Color(255, 255, 255));
        pnlEspacios.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(42, 99, 153))); // NOI18N
        pnlEspacios.setForeground(new java.awt.Color(42, 99, 153));

        lblEspacios.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        lblEspacios.setForeground(new java.awt.Color(42, 99, 153));
        lblEspacios.setText("Espacios");

        lblImagenEspacios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/drawer.png"))); // NOI18N
        lblImagenEspacios.setText("jLabel9");

        btnEspacios.setBackground(new java.awt.Color(47, 102, 153));
        btnEspacios.setForeground(new java.awt.Color(255, 255, 255));
        btnEspacios.setText("Gestionar Espacios");

        javax.swing.GroupLayout pnlEspaciosLayout = new javax.swing.GroupLayout(pnlEspacios);
        pnlEspacios.setLayout(pnlEspaciosLayout);
        pnlEspaciosLayout.setHorizontalGroup(
            pnlEspaciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEspaciosLayout.createSequentialGroup()
                .addGroup(pnlEspaciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlEspaciosLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(pnlEspaciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblImagenEspacios, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEspacios)))
                    .addGroup(pnlEspaciosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnEspacios)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlEspaciosLayout.setVerticalGroup(
            pnlEspaciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlEspaciosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblImagenEspacios)
                .addGap(53, 53, 53)
                .addComponent(lblEspacios)
                .addGap(30, 30, 30)
                .addComponent(btnEspacios)
                .addGap(24, 24, 24))
        );

        pnlClientes.setBackground(new java.awt.Color(255, 255, 255));
        pnlClientes.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        lblClientes.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        lblClientes.setForeground(new java.awt.Color(42, 99, 153));
        lblClientes.setText("Clientes");

        lblImagenClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/contacts.png"))); // NOI18N
        lblImagenClientes.setText("jLabel9");

        btnClientes.setBackground(new java.awt.Color(47, 102, 153));
        btnClientes.setForeground(new java.awt.Color(255, 255, 255));
        btnClientes.setText("Gestionar Clientes");
        btnClientes.addActionListener(this::btnClientesActionPerformed);

        javax.swing.GroupLayout pnlClientesLayout = new javax.swing.GroupLayout(pnlClientes);
        pnlClientes.setLayout(pnlClientesLayout);
        pnlClientesLayout.setHorizontalGroup(
            pnlClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlClientesLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(pnlClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblClientes)
                    .addComponent(lblImagenClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlClientesLayout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(btnClientes)
                .addGap(20, 20, 20))
        );
        pnlClientesLayout.setVerticalGroup(
            pnlClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlClientesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblImagenClientes)
                .addGap(57, 57, 57)
                .addComponent(lblClientes)
                .addGap(27, 27, 27)
                .addComponent(btnClientes)
                .addGap(23, 23, 23))
        );

        pnlServicios.setBackground(new java.awt.Color(255, 255, 255));
        pnlServicios.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        lblServicios.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        lblServicios.setForeground(new java.awt.Color(42, 99, 153));
        lblServicios.setText("Servicios");

        lblImagenServicios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/application_x_desktop (4).png"))); // NOI18N
        lblImagenServicios.setText("jLabel9");

        btnServicios.setBackground(new java.awt.Color(47, 102, 153));
        btnServicios.setForeground(new java.awt.Color(255, 255, 255));
        btnServicios.setText("Gestionar Servicios");
        btnServicios.addActionListener(this::btnServiciosActionPerformed);

        javax.swing.GroupLayout pnlServiciosLayout = new javax.swing.GroupLayout(pnlServicios);
        pnlServicios.setLayout(pnlServiciosLayout);
        pnlServiciosLayout.setHorizontalGroup(
            pnlServiciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlServiciosLayout.createSequentialGroup()
                .addGap(0, 17, Short.MAX_VALUE)
                .addComponent(btnServicios)
                .addGap(16, 16, 16))
            .addGroup(pnlServiciosLayout.createSequentialGroup()
                .addGroup(pnlServiciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlServiciosLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(lblServicios))
                    .addGroup(pnlServiciosLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(lblImagenServicios, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlServiciosLayout.setVerticalGroup(
            pnlServiciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlServiciosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblImagenServicios)
                .addGap(57, 57, 57)
                .addComponent(lblServicios)
                .addGap(27, 27, 27)
                .addComponent(btnServicios)
                .addGap(23, 23, 23))
        );

        pnlEmpleados.setBackground(new java.awt.Color(255, 255, 255));
        pnlEmpleados.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        lblEmpleados.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        lblEmpleados.setForeground(new java.awt.Color(42, 99, 153));
        lblEmpleados.setText("Empleados");

        lblImagenEmpleados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/contact (4).png"))); // NOI18N
        lblImagenEmpleados.setText("jLabel9");

        btnEmpleados.setBackground(new java.awt.Color(47, 102, 153));
        btnEmpleados.setForeground(new java.awt.Color(255, 255, 255));
        btnEmpleados.setText("Gestionar Empleados");
        btnEmpleados.addActionListener(this::btnEmpleadosActionPerformed);

        javax.swing.GroupLayout pnlEmpleadosLayout = new javax.swing.GroupLayout(pnlEmpleados);
        pnlEmpleados.setLayout(pnlEmpleadosLayout);
        pnlEmpleadosLayout.setHorizontalGroup(
            pnlEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlEmpleadosLayout.createSequentialGroup()
                .addGap(0, 12, Short.MAX_VALUE)
                .addComponent(btnEmpleados)
                .addGap(16, 16, 16))
            .addGroup(pnlEmpleadosLayout.createSequentialGroup()
                .addGroup(pnlEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlEmpleadosLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(lblEmpleados))
                    .addGroup(pnlEmpleadosLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(lblImagenEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlEmpleadosLayout.setVerticalGroup(
            pnlEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlEmpleadosLayout.createSequentialGroup()
                .addContainerGap(80, Short.MAX_VALUE)
                .addComponent(lblImagenEmpleados)
                .addGap(57, 57, 57)
                .addComponent(lblEmpleados)
                .addGap(27, 27, 27)
                .addComponent(btnEmpleados)
                .addGap(23, 23, 23))
        );

        pnlContratos.setBackground(new java.awt.Color(255, 255, 255));
        pnlContratos.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        lblContratos.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        lblContratos.setForeground(new java.awt.Color(42, 99, 153));
        lblContratos.setText("Contratos");

        lblImagenContratos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/application_vnd.oasis.opendocument.spreadsheet (4).png"))); // NOI18N
        lblImagenContratos.setText("jLabel9");

        btnContratos.setBackground(new java.awt.Color(47, 102, 153));
        btnContratos.setForeground(new java.awt.Color(255, 255, 255));
        btnContratos.setText("Gestionar Contratos");
        btnContratos.addActionListener(this::btnContratosActionPerformed);

        javax.swing.GroupLayout pnlContratosLayout = new javax.swing.GroupLayout(pnlContratos);
        pnlContratos.setLayout(pnlContratosLayout);
        pnlContratosLayout.setHorizontalGroup(
            pnlContratosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlContratosLayout.createSequentialGroup()
                .addGap(0, 22, Short.MAX_VALUE)
                .addComponent(btnContratos)
                .addGap(16, 16, 16))
            .addGroup(pnlContratosLayout.createSequentialGroup()
                .addGroup(pnlContratosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlContratosLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(lblContratos))
                    .addGroup(pnlContratosLayout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(lblImagenContratos, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlContratosLayout.setVerticalGroup(
            pnlContratosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlContratosLayout.createSequentialGroup()
                .addContainerGap(80, Short.MAX_VALUE)
                .addComponent(lblImagenContratos)
                .addGap(57, 57, 57)
                .addComponent(lblContratos)
                .addGap(27, 27, 27)
                .addComponent(btnContratos)
                .addGap(23, 23, 23))
        );

        btnSalir.setBackground(new java.awt.Color(47, 102, 153));
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Cancel.png"))); // NOI18N
        btnSalir.setText("Salir del Sistema");
        btnSalir.addActionListener(this::btnSalirActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlEncabezado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSalir)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(pnlEspacios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(pnlClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(pnlServicios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(pnlEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(pnlContratos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(pnlEncabezado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlContratos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlEmpleados, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlEspacios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlServicios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSalir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmpleadosActionPerformed
    VistaEmpleado vista = new VistaEmpleado();
    vista.setLocationRelativeTo(null);
    vista.setVisible(true);

    this.dispose();
    }//GEN-LAST:event_btnEmpleadosActionPerformed

    private void btnContratosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContratosActionPerformed
    VistaContrato vistaContrato = new VistaContrato();
    vistaContrato.setLocationRelativeTo(null);
    vistaContrato.setVisible(true);

    this.dispose();
    }//GEN-LAST:event_btnContratosActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed


    private void btnClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientesActionPerformed
        VistaCliente vistaCliente = new VistaCliente();
    vistaCliente.setLocationRelativeTo(null);
    vistaCliente.setVisible(true);

    this.dispose();
    }//GEN-LAST:event_btnClientesActionPerformed

    private void btnServiciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnServiciosActionPerformed
        VistaServicio vistaServicio = new VistaServicio();
        vistaServicio.setLocationRelativeTo(null);
        vistaServicio.setVisible(true);

    this.dispose();
    }//GEN-LAST:event_btnServiciosActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VistaMenuPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClientes;
    private javax.swing.JButton btnContratos;
    private javax.swing.JButton btnEmpleados;
    private javax.swing.JButton btnEspacios;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnServicios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblClientes;
    private javax.swing.JLabel lblContratos;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JLabel lblEmpleados;
    private javax.swing.JLabel lblEspacios;
    private javax.swing.JLabel lblImagenClientes;
    private javax.swing.JLabel lblImagenContratos;
    private javax.swing.JLabel lblImagenEmpleados;
    private javax.swing.JLabel lblImagenEspacios;
    private javax.swing.JLabel lblImagenServicios;
    private javax.swing.JLabel lblServicios;
    private javax.swing.JLabel lblStorageBox;
    private javax.swing.JLabel lblSubtitulo;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel pnlClientes;
    private javax.swing.JPanel pnlContratos;
    private javax.swing.JPanel pnlEmpleados;
    private javax.swing.JPanel pnlEncabezado;
    private javax.swing.JPanel pnlEspacios;
    private javax.swing.JPanel pnlServicios;
    // End of variables declaration//GEN-END:variables
}
