/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import Clientes.cliente;
import contratos.Contrato;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import servicios.Servicio;
import storageBox.Views;
import storageBox.StorageBoxController;

/**
 *
 * @author marii
 */
public class VistaContrato extends javax.swing.JFrame implements Views<Contrato> {
    private StorageBoxController controlador;
    private ArrayList<Servicio> serviciosSeleccionados;
    private cliente clienteSeleccionado;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VistaContrato.class.getName());

    /**
     * Creates new form VistaContrato
     */
    public VistaContrato() {
        initComponents();
        controlador = StorageBoxController.getInstance(this);

        serviciosSeleccionados = new ArrayList<>();

    DefaultTableModel modelo = (DefaultTableModel) tblServicios.getModel();
    modelo.setRowCount(0);
    
    }
    @Override
    public void showData(Contrato contrato) {
    txtNumeroContrato.setText(String.valueOf(contrato.getNumeroContrato()));

    txtCedula.setText(contrato.getCliente().getCedula());

    txtNombreCliente.setText(contrato.getCliente().getNombre());

    txtEstado.setText(contrato.getEstado().toString());

    txtSubtotal.setText(String.valueOf(contrato.getSubtotal()));

    txtImpuestos.setText(String.valueOf(contrato.getImpuestos()));

    txtTotal.setText(String.valueOf(contrato.getTotal()));
    
    txtEspacioAsignado.setText(String.valueOf(contrato.getEspacio().getId_Espacio()));

    txtFechaInicio.setText(contrato.getFechaInicio().toString());

    txtFechaFin.setText(contrato.getFechaFinal().toString());
     }

    @Override
    public void showError(String message) {
    javax.swing.JOptionPane.showMessageDialog(
            this,
            message,
            "Error",
            javax.swing.JOptionPane.ERROR_MESSAGE
    );
}

    @Override
     public void showMessage(String message) {
    javax.swing.JOptionPane.showMessageDialog(
            this,
            message
    );
}

    @Override
    public void clear() {
    txtNumeroContrato.setText("");
    txtCedula.setText("");
    txtNombreCliente.setText("");

    txtEspaciosDisponibles.setText("");
    txtEspacioAsignado.setText("");

    txtEstado.setText("PENDIENTE");

    txtSubtotal.setText("");
    txtImpuestos.setText("");
    txtTotal.setText("");

    javax.swing.table.DefaultTableModel modelo =
            (javax.swing.table.DefaultTableModel) tblServicios.getModel();
    modelo.setRowCount(0);   
}
    public void agregarServicioSeleccionado(Servicio servicio) {

    serviciosSeleccionados.add(servicio);
    DefaultTableModel modelo = (DefaultTableModel) tblServicios.getModel();

    modelo.addRow(new Object[]{
        servicio.getNombre(),
        servicio.getDescripcion(),
        servicio.getPrecio()
    });
}
    public void agregarClienteSeleccionado(cliente cliente) {

    this.clienteSeleccionado = cliente;

    txtCedula.setText(cliente.getCedula());
    txtNombreCliente.setText(cliente.getNombre());
}
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlContrato = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblNumeroContrato = new javax.swing.JLabel();
        txtNumeroContrato = new javax.swing.JTextField();
        pnlCliente = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblCedula = new javax.swing.JLabel();
        txtCedula = new javax.swing.JTextField();
        btnBuscarCliente = new javax.swing.JButton();
        lblNombreCliente = new javax.swing.JLabel();
        txtNombreCliente = new javax.swing.JTextField();
        pnlEspacio = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblTipodeEspacio = new javax.swing.JLabel();
        cmbTipoEspacio = new javax.swing.JComboBox<>();
        btnVerEspacios = new javax.swing.JButton();
        lblEspaciosDisponibles = new javax.swing.JLabel();
        txtEspaciosDisponibles = new javax.swing.JTextField();
        lblEspaciosDisponibles1 = new javax.swing.JLabel();
        txtEspacioAsignado = new javax.swing.JTextField();
        pnlFechas = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtFechaInicio = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtFechaFin = new javax.swing.JTextField();
        pnlEstado = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        lblEstadoActual = new javax.swing.JLabel();
        txtEstado = new javax.swing.JTextField();
        btnLimpiar1 = new javax.swing.JButton();
        pnlServicios = new javax.swing.JPanel();
        lblServiciosAdicionales = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblServicios = new javax.swing.JTable();
        btnAgregarServicio = new javax.swing.JButton();
        btnEliminarServicio = new javax.swing.JButton();
        pnlCostos = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        lblSubTotal = new javax.swing.JLabel();
        txtSubtotal = new javax.swing.JTextField();
        lblImpuestos = new javax.swing.JLabel();
        txtImpuestos = new javax.swing.JTextField();
        lblTotal = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        pnlAcciones = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        btnCrearContrato = new javax.swing.JButton();
        btnActivarContrato = new javax.swing.JButton();
        btnFinalizarContrato = new javax.swing.JButton();
        btnCancelarContrato = new javax.swing.JButton();
        btnBuscarContrato = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("StorageBox- Contrato");

        pnlContrato.setBackground(new java.awt.Color(255, 255, 255));

        lblTitulo.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(42, 99, 153));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("CONTRATO DE ALQUILER");

        lblNumeroContrato.setText("Número de contrato:");

        txtNumeroContrato.setEditable(false);

        pnlCliente.setBackground(new java.awt.Color(255, 255, 255));
        pnlCliente.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(42, 99, 153));
        jLabel1.setText("1. CLIENTE");

        lblCedula.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        lblCedula.setText("Cédula: ");

        txtCedula.setEditable(false);

        btnBuscarCliente.setBackground(new java.awt.Color(42, 99, 153));
        btnBuscarCliente.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Search.png"))); // NOI18N
        btnBuscarCliente.setText("Buscar");
        btnBuscarCliente.addActionListener(this::btnBuscarClienteActionPerformed);

        lblNombreCliente.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        lblNombreCliente.setText("Nombre:");

        txtNombreCliente.setEditable(false);

        javax.swing.GroupLayout pnlClienteLayout = new javax.swing.GroupLayout(pnlCliente);
        pnlCliente.setLayout(pnlClienteLayout);
        pnlClienteLayout.setHorizontalGroup(
            pnlClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlClienteLayout.createSequentialGroup()
                        .addComponent(lblNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNombreCliente))
                    .addGroup(pnlClienteLayout.createSequentialGroup()
                        .addGroup(pnlClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(pnlClienteLayout.createSequentialGroup()
                                .addComponent(lblCedula)
                                .addGap(18, 18, 18)
                                .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnBuscarCliente)))
                        .addGap(0, 10, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlClienteLayout.setVerticalGroup(
            pnlClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCedula)
                    .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarCliente))
                .addGap(18, 18, 18)
                .addGroup(pnlClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreCliente)
                    .addComponent(txtNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlEspacio.setBackground(new java.awt.Color(255, 255, 255));
        pnlEspacio.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(42, 99, 153));
        jLabel2.setText("2. ESPACIO");

        lblTipodeEspacio.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        lblTipodeEspacio.setText("Tipo de Espacio: ");

        cmbTipoEspacio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnVerEspacios.setBackground(new java.awt.Color(42, 99, 153));
        btnVerEspacios.setForeground(new java.awt.Color(255, 255, 255));
        btnVerEspacios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Search.png"))); // NOI18N
        btnVerEspacios.setText("Ver espacios disponibles");

        lblEspaciosDisponibles.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        lblEspaciosDisponibles.setText("Espacios disponibles:");

        txtEspaciosDisponibles.setEditable(false);

        lblEspaciosDisponibles1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        lblEspaciosDisponibles1.setText("Espacio asignado:");

        txtEspacioAsignado.setEditable(false);

        javax.swing.GroupLayout pnlEspacioLayout = new javax.swing.GroupLayout(pnlEspacio);
        pnlEspacio.setLayout(pnlEspacioLayout);
        pnlEspacioLayout.setHorizontalGroup(
            pnlEspacioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEspacioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlEspacioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlEspacioLayout.createSequentialGroup()
                        .addGroup(pnlEspacioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblEspaciosDisponibles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblTipodeEspacio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(pnlEspacioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlEspacioLayout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(lblEspaciosDisponibles1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlEspacioLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbTipoEspacio, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnVerEspacios, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabel2)
                    .addGroup(pnlEspacioLayout.createSequentialGroup()
                        .addComponent(txtEspaciosDisponibles, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtEspacioAsignado, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(19, 19, 19))
        );
        pnlEspacioLayout.setVerticalGroup(
            pnlEspacioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEspacioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlEspacioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipodeEspacio)
                    .addComponent(cmbTipoEspacio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVerEspacios))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlEspacioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEspaciosDisponibles)
                    .addComponent(lblEspaciosDisponibles1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlEspacioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEspaciosDisponibles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEspacioAsignado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pnlFechas.setBackground(new java.awt.Color(255, 255, 255));
        pnlFechas.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(42, 99, 153));
        jLabel3.setText("3. FECHAS");

        jLabel4.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel4.setText("Fecha de inicio:");

        txtFechaInicio.setEditable(false);
        txtFechaInicio.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtFechaInicio.setText("dd/mm/aaaa");

        jLabel5.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel5.setText("Fecha de finalización :");

        txtFechaFin.setEditable(false);
        txtFechaFin.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtFechaFin.setText("dd/mm/aaaa");

        javax.swing.GroupLayout pnlFechasLayout = new javax.swing.GroupLayout(pnlFechas);
        pnlFechas.setLayout(pnlFechasLayout);
        pnlFechasLayout.setHorizontalGroup(
            pnlFechasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFechasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlFechasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(pnlFechasLayout.createSequentialGroup()
                        .addGroup(pnlFechasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(txtFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addGroup(pnlFechasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(txtFechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlFechasLayout.setVerticalGroup(
            pnlFechasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFechasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlFechasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlFechasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pnlEstado.setBackground(new java.awt.Color(255, 255, 255));
        pnlEstado.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel6.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(42, 99, 153));
        jLabel6.setText("4. ESTADO");

        lblEstadoActual.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        lblEstadoActual.setText("Estado actual:");

        txtEstado.setEditable(false);
        txtEstado.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtEstado.setText("PENDIENTE");

        btnLimpiar1.setBackground(new java.awt.Color(42, 99, 153));
        btnLimpiar1.setForeground(new java.awt.Color(255, 255, 255));
        btnLimpiar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Cancel.png"))); // NOI18N
        btnLimpiar1.setText("Regresar");
        btnLimpiar1.addActionListener(this::btnLimpiar1ActionPerformed);

        javax.swing.GroupLayout pnlEstadoLayout = new javax.swing.GroupLayout(pnlEstado);
        pnlEstado.setLayout(pnlEstadoLayout);
        pnlEstadoLayout.setHorizontalGroup(
            pnlEstadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEstadoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlEstadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlEstadoLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lblEstadoActual)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(161, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlEstadoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLimpiar1)
                .addContainerGap())
        );
        pnlEstadoLayout.setVerticalGroup(
            pnlEstadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEstadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(pnlEstadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEstadoActual)
                    .addComponent(txtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLimpiar1)
                .addContainerGap())
        );

        pnlServicios.setBackground(new java.awt.Color(255, 255, 255));
        pnlServicios.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        lblServiciosAdicionales.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        lblServiciosAdicionales.setForeground(new java.awt.Color(42, 99, 153));
        lblServiciosAdicionales.setText("5. SERVICIOS ADICIONALES");

        tblServicios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Servicio", "Descripción", "Precio unitario"
            }
        ));
        jScrollPane1.setViewportView(tblServicios);

        btnAgregarServicio.setBackground(new java.awt.Color(42, 99, 153));
        btnAgregarServicio.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregarServicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Save.png"))); // NOI18N
        btnAgregarServicio.setText("Agregar servicio");
        btnAgregarServicio.addActionListener(this::btnAgregarServicioActionPerformed);

        btnEliminarServicio.setBackground(new java.awt.Color(42, 99, 153));
        btnEliminarServicio.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarServicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Delete.png"))); // NOI18N
        btnEliminarServicio.setText("Eliminar servicio");
        btnEliminarServicio.addActionListener(this::btnEliminarServicioActionPerformed);

        javax.swing.GroupLayout pnlServiciosLayout = new javax.swing.GroupLayout(pnlServicios);
        pnlServicios.setLayout(pnlServiciosLayout);
        pnlServiciosLayout.setHorizontalGroup(
            pnlServiciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlServiciosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlServiciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblServiciosAdicionales)
                    .addGroup(pnlServiciosLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addGroup(pnlServiciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnAgregarServicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnEliminarServicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        pnlServiciosLayout.setVerticalGroup(
            pnlServiciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlServiciosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblServiciosAdicionales)
                .addGroup(pnlServiciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlServiciosLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(pnlServiciosLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(btnAgregarServicio)
                        .addGap(30, 30, 30)
                        .addComponent(btnEliminarServicio)
                        .addContainerGap(21, Short.MAX_VALUE))))
        );

        pnlCostos.setBackground(new java.awt.Color(255, 255, 255));
        pnlCostos.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel7.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(42, 99, 153));
        jLabel7.setText("6. COSTOS");

        lblSubTotal.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        lblSubTotal.setText("Subtotal:");

        txtSubtotal.setEditable(false);

        lblImpuestos.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        lblImpuestos.setText("Impuestos (13%):");

        txtImpuestos.setEditable(false);

        lblTotal.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        lblTotal.setText("Total: ");

        txtTotal.setEditable(false);

        javax.swing.GroupLayout pnlCostosLayout = new javax.swing.GroupLayout(pnlCostos);
        pnlCostos.setLayout(pnlCostosLayout);
        pnlCostosLayout.setHorizontalGroup(
            pnlCostosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCostosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCostosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCostosLayout.createSequentialGroup()
                        .addComponent(lblImpuestos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtImpuestos))
                    .addGroup(pnlCostosLayout.createSequentialGroup()
                        .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(txtTotal))
                    .addComponent(jSeparator1)
                    .addGroup(pnlCostosLayout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnlCostosLayout.createSequentialGroup()
                        .addComponent(lblSubTotal)
                        .addGap(54, 54, 54)
                        .addComponent(txtSubtotal)))
                .addContainerGap())
        );
        pnlCostosLayout.setVerticalGroup(
            pnlCostosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCostosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlCostosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSubTotal)
                    .addComponent(txtSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlCostosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblImpuestos)
                    .addComponent(txtImpuestos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addGroup(pnlCostosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTotal)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlAcciones.setBackground(new java.awt.Color(255, 255, 255));
        pnlAcciones.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel8.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(42, 99, 153));
        jLabel8.setText("7. ACCIONES");

        btnCrearContrato.setBackground(new java.awt.Color(42, 99, 153));
        btnCrearContrato.setForeground(new java.awt.Color(255, 255, 255));
        btnCrearContrato.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/New.png"))); // NOI18N
        btnCrearContrato.setText("Crear contrato");
        btnCrearContrato.addActionListener(this::btnCrearContratoActionPerformed);

        btnActivarContrato.setBackground(new java.awt.Color(42, 99, 153));
        btnActivarContrato.setForeground(new java.awt.Color(255, 255, 255));
        btnActivarContrato.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Edit.png"))); // NOI18N
        btnActivarContrato.setText("Activar contrato");
        btnActivarContrato.addActionListener(this::btnActivarContratoActionPerformed);

        btnFinalizarContrato.setBackground(new java.awt.Color(42, 99, 153));
        btnFinalizarContrato.setForeground(new java.awt.Color(255, 255, 255));
        btnFinalizarContrato.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Save.png"))); // NOI18N
        btnFinalizarContrato.setText("Finalizar contrato");
        btnFinalizarContrato.addActionListener(this::btnFinalizarContratoActionPerformed);

        btnCancelarContrato.setBackground(new java.awt.Color(42, 99, 153));
        btnCancelarContrato.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelarContrato.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Cancel.png"))); // NOI18N
        btnCancelarContrato.setText("Cancelar contrato");
        btnCancelarContrato.addActionListener(this::btnCancelarContratoActionPerformed);

        btnBuscarContrato.setBackground(new java.awt.Color(42, 99, 153));
        btnBuscarContrato.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscarContrato.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Search.png"))); // NOI18N
        btnBuscarContrato.setText("Buscar contrato");
        btnBuscarContrato.addActionListener(this::btnBuscarContratoActionPerformed);

        btnLimpiar.setBackground(new java.awt.Color(42, 99, 153));
        btnLimpiar.setForeground(new java.awt.Color(255, 255, 255));
        btnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/New.png"))); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(this::btnLimpiarActionPerformed);

        javax.swing.GroupLayout pnlAccionesLayout = new javax.swing.GroupLayout(pnlAcciones);
        pnlAcciones.setLayout(pnlAccionesLayout);
        pnlAccionesLayout.setHorizontalGroup(
            pnlAccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAccionesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCrearContrato, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnActivarContrato, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnFinalizarContrato, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCancelarContrato, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnBuscarContrato, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                .addGap(26, 26, 26)
                .addComponent(btnLimpiar, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                .addGap(24, 24, 24))
        );
        pnlAccionesLayout.setVerticalGroup(
            pnlAccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAccionesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGap(26, 26, 26)
                .addGroup(pnlAccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCrearContrato)
                    .addComponent(btnActivarContrato)
                    .addComponent(btnFinalizarContrato)
                    .addComponent(btnCancelarContrato)
                    .addComponent(btnBuscarContrato)
                    .addComponent(btnLimpiar))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlContratoLayout = new javax.swing.GroupLayout(pnlContrato);
        pnlContrato.setLayout(pnlContratoLayout);
        pnlContratoLayout.setHorizontalGroup(
            pnlContratoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContratoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlContratoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlContratoLayout.createSequentialGroup()
                        .addComponent(pnlAcciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(pnlContratoLayout.createSequentialGroup()
                        .addGroup(pnlContratoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(pnlFechas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnlCliente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlContratoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnlEspacio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnlEstado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(pnlContratoLayout.createSequentialGroup()
                        .addGroup(pnlContratoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlContratoLayout.createSequentialGroup()
                                .addComponent(lblNumeroContrato)
                                .addGap(18, 18, 18)
                                .addComponent(txtNumeroContrato, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(197, 197, 197)
                                .addComponent(lblTitulo)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(pnlContratoLayout.createSequentialGroup()
                                .addComponent(pnlServicios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(pnlCostos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(6, 6, 6))))
        );
        pnlContratoLayout.setVerticalGroup(
            pnlContratoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContratoLayout.createSequentialGroup()
                .addGroup(pnlContratoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlContratoLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(pnlContratoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNumeroContrato)
                            .addComponent(txtNumeroContrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlContratoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblTitulo)
                        .addGap(28, 28, 28)))
                .addGroup(pnlContratoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlEspacio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlContratoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlEstado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlFechas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlContratoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlCostos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlServicios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlAcciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlContrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlContrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearContratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearContratoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCrearContratoActionPerformed

    private void btnActivarContratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActivarContratoActionPerformed
        if (txtNumeroContrato.getText().isEmpty()) {
        showError("Primero debe seleccionar un contrato");
        return;
    }
    int numeroContrato = Integer.parseInt(txtNumeroContrato.getText());

    if (controlador.activarContrato(numeroContrato)) {
        txtEstado.setText("ACTIVO");
    }
    }//GEN-LAST:event_btnActivarContratoActionPerformed

    private void btnFinalizarContratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarContratoActionPerformed
      
    if (txtNumeroContrato.getText().isEmpty()) {
        showError("Primero debe seleccionar un contrato");
        return;
    }

    int numeroContrato = Integer.parseInt(txtNumeroContrato.getText());

    if (controlador.finalizarContrato(numeroContrato)) {
        txtEstado.setText("FINALIZADO");
    }

    }//GEN-LAST:event_btnFinalizarContratoActionPerformed

    private void btnCancelarContratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarContratoActionPerformed
         if (txtNumeroContrato.getText().isEmpty()) {
        showError("Primero debe seleccionar un contrato");
        return;
    }

    int numeroContrato =
            Integer.parseInt(txtNumeroContrato.getText());

    if (controlador.cancelarContrato(numeroContrato)) {
        txtEstado.setText("CANCELADO");
    }
    }//GEN-LAST:event_btnCancelarContratoActionPerformed

    private void btnBuscarContratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarContratoActionPerformed
    VistaBuscarContrato vistaBuscar = new VistaBuscarContrato(this);
    vistaBuscar.setLocationRelativeTo(this);
    vistaBuscar.setVisible(true);
    }//GEN-LAST:event_btnBuscarContratoActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        clear();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnLimpiar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiar1ActionPerformed
    VistaMenuPrincipal menu = new VistaMenuPrincipal();
    menu.setLocationRelativeTo(null);
    menu.setVisible(true);

    this.dispose();
    }//GEN-LAST:event_btnLimpiar1ActionPerformed

    private void btnAgregarServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarServicioActionPerformed
       VistaBuscarServicio buscar = new VistaBuscarServicio(this);

       buscar.setLocationRelativeTo(this);
       buscar.setVisible(true);

    this.setVisible(false);
    }//GEN-LAST:event_btnAgregarServicioActionPerformed

    private void btnEliminarServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarServicioActionPerformed
       int fila = tblServicios.getSelectedRow();

    if (fila == -1) {
        showError("Debe seleccionar un servicio");
        return;
    }

    serviciosSeleccionados.remove(fila);

    DefaultTableModel modelo = (DefaultTableModel) tblServicios.getModel();

    modelo.removeRow(fila);
    }//GEN-LAST:event_btnEliminarServicioActionPerformed

    private void btnBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarClienteActionPerformed
        VistaBuscarCliente buscar = new VistaBuscarCliente(this);

        buscar.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnBuscarClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VistaContrato().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActivarContrato;
    private javax.swing.JButton btnAgregarServicio;
    private javax.swing.JButton btnBuscarCliente;
    private javax.swing.JButton btnBuscarContrato;
    private javax.swing.JButton btnCancelarContrato;
    private javax.swing.JButton btnCrearContrato;
    private javax.swing.JButton btnEliminarServicio;
    private javax.swing.JButton btnFinalizarContrato;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnLimpiar1;
    private javax.swing.JButton btnVerEspacios;
    private javax.swing.JComboBox<String> cmbTipoEspacio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblCedula;
    private javax.swing.JLabel lblEspaciosDisponibles;
    private javax.swing.JLabel lblEspaciosDisponibles1;
    private javax.swing.JLabel lblEstadoActual;
    private javax.swing.JLabel lblImpuestos;
    private javax.swing.JLabel lblNombreCliente;
    private javax.swing.JLabel lblNumeroContrato;
    private javax.swing.JLabel lblServiciosAdicionales;
    private javax.swing.JLabel lblSubTotal;
    private javax.swing.JLabel lblTipodeEspacio;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JPanel pnlAcciones;
    private javax.swing.JPanel pnlCliente;
    private javax.swing.JPanel pnlContrato;
    private javax.swing.JPanel pnlCostos;
    private javax.swing.JPanel pnlEspacio;
    private javax.swing.JPanel pnlEstado;
    private javax.swing.JPanel pnlFechas;
    private javax.swing.JPanel pnlServicios;
    private javax.swing.JTable tblServicios;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtEspacioAsignado;
    private javax.swing.JTextField txtEspaciosDisponibles;
    private javax.swing.JTextField txtEstado;
    private javax.swing.JTextField txtFechaFin;
    private javax.swing.JTextField txtFechaInicio;
    private javax.swing.JTextField txtImpuestos;
    private javax.swing.JTextField txtNombreCliente;
    private javax.swing.JTextField txtNumeroContrato;
    private javax.swing.JTextField txtSubtotal;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
