/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import contratos.Contrato;
import contratos.EstadoContrato;
import java.time.LocalDate;
import java.util.Iterator;
import javax.swing.table.DefaultTableModel;
import storageBox.StorageBoxController;
import storageBox.Views;

/**
 *
 * @author marii
 */
public class VistaBuscarContrato extends javax.swing.JFrame implements Views<Contrato> {
    private VistaContrato vistaContrato;
    private StorageBoxController controlador;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VistaBuscarContrato.class.getName());

    /**
     * Creates new form VistaBuscarContrato
     */
    public VistaBuscarContrato() {
        initComponents();
        this.controlador = StorageBoxController.getInstance(this);
        cargarEstados();
        cargarTabla();
    }
    
    public VistaBuscarContrato(VistaContrato vistaContrato) {
       initComponents();
       this.vistaContrato = vistaContrato;
       this.controlador = StorageBoxController.getInstance(this);
       controlador.setView(this);
       cargarEstados();
       cargarTabla();
}
    @Override
     public void showError(String message) {
    javax.swing.JOptionPane.showMessageDialog(
            this,
            message,
            "Error",
            javax.swing.JOptionPane.ERROR_MESSAGE
    );
}
     @Override
    public void showMessage(String message) {
    javax.swing.JOptionPane.showMessageDialog(this, message);
    }

    @Override
    public void showData(Contrato contrato) {
    txtNumeroContrato.setText(String.valueOf(contrato.getNumeroContrato()));

    txtCedula.setText(contrato.getCliente().getCedula());

    txtEspacio.setText(String.valueOf(contrato.getEspacio().getId_Espacio()));

    txtFechaDesde.setText(contrato.getFechaInicio().toString());

    txtFechaHasta.setText(contrato.getFechaFinal().toString());

    cmbEstado.setSelectedItem(contrato.getEstado().toString());
    }

    @Override
    public void clear() {
    }
    
    private void cargarTabla() {

    DefaultTableModel modelo = (DefaultTableModel) tblContratos.getModel();
    modelo.setRowCount(0);
    
    Iterator<Contrato> contratos = controlador.getContratos();

    if (contratos == null) {
        return;
    }

    while (contratos.hasNext()) {
        Contrato contrato = contratos.next();

        modelo.addRow(new Object[]{
            contrato.getNumeroContrato(),
            contrato.getCliente().getCedula(),
            contrato.getEspacio().getId_Espacio(),
            contrato.getFechaInicio(),
            contrato.getFechaFinal(),
            contrato.getEstado(),
            contrato.getTotal()
        });
    }
}
    private void cargarEstados() {

    cmbEstado.removeAllItems();
    cmbEstado.addItem("Todos");

    for (EstadoContrato estado : EstadoContrato.values()) {
        cmbEstado.addItem(estado.toString());
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pnlBuscarContacto = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        pnlFlitrosDeBusqueda = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lblNumdeContrato = new javax.swing.JLabel();
        txtNumeroContrato = new javax.swing.JTextField();
        lblNumdeContrato1 = new javax.swing.JLabel();
        txtCedula = new javax.swing.JTextField();
        lblNumdeContrato2 = new javax.swing.JLabel();
        txtEspacio = new javax.swing.JTextField();
        lblNumdeContrato3 = new javax.swing.JLabel();
        txtFechaDesde = new javax.swing.JTextField();
        lblNumdeContrato4 = new javax.swing.JLabel();
        txtFechaHasta = new javax.swing.JTextField();
        lblNumdeContrato5 = new javax.swing.JLabel();
        cmbEstado = new javax.swing.JComboBox<>();
        btnBuscar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        pnlResultados = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        scllResultados = new javax.swing.JScrollPane();
        tblContratos = new javax.swing.JTable();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Storage Box - Buscar Contrato");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        pnlBuscarContacto.setBackground(new java.awt.Color(42, 99, 153));
        pnlBuscarContacto.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("StorageBox ");

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Buscar Contrato");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/archive-48.png"))); // NOI18N
        jLabel5.setText("jLabel5");

        javax.swing.GroupLayout pnlBuscarContactoLayout = new javax.swing.GroupLayout(pnlBuscarContacto);
        pnlBuscarContacto.setLayout(pnlBuscarContactoLayout);
        pnlBuscarContactoLayout.setHorizontalGroup(
            pnlBuscarContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBuscarContactoLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        pnlBuscarContactoLayout.setVerticalGroup(
            pnlBuscarContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBuscarContactoLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(pnlBuscarContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5))
                .addGap(8, 8, 8))
        );

        pnlFlitrosDeBusqueda.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel3.setText("Filtros de búsqueda:");

        lblNumdeContrato.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        lblNumdeContrato.setText("Número de contrato:");

        lblNumdeContrato1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        lblNumdeContrato1.setText("Cliente (cédula):");

        lblNumdeContrato2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        lblNumdeContrato2.setText("Espacio:");

        lblNumdeContrato3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        lblNumdeContrato3.setText("Fecha desde:");

        lblNumdeContrato4.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        lblNumdeContrato4.setText("Fecha hasta:");

        lblNumdeContrato5.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        lblNumdeContrato5.setText("Estado:");

        cmbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Search.png"))); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(this::btnBuscarActionPerformed);

        btnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/New.png"))); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(this::btnLimpiarActionPerformed);

        javax.swing.GroupLayout pnlFlitrosDeBusquedaLayout = new javax.swing.GroupLayout(pnlFlitrosDeBusqueda);
        pnlFlitrosDeBusqueda.setLayout(pnlFlitrosDeBusquedaLayout);
        pnlFlitrosDeBusquedaLayout.setHorizontalGroup(
            pnlFlitrosDeBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFlitrosDeBusquedaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlFlitrosDeBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblNumdeContrato)
                    .addComponent(txtNumeroContrato))
                .addGroup(pnlFlitrosDeBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlFlitrosDeBusquedaLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(lblNumdeContrato1)
                        .addGap(37, 37, 37)
                        .addComponent(lblNumdeContrato2)
                        .addGap(78, 78, 78)
                        .addComponent(lblNumdeContrato3)
                        .addGap(56, 56, 56)
                        .addComponent(lblNumdeContrato4)
                        .addGap(58, 58, 58)
                        .addComponent(lblNumdeContrato5))
                    .addGroup(pnlFlitrosDeBusquedaLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtEspacio, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtFechaDesde, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtFechaHasta, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cmbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFlitrosDeBusquedaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );
        pnlFlitrosDeBusquedaLayout.setVerticalGroup(
            pnlFlitrosDeBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFlitrosDeBusquedaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlFlitrosDeBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumdeContrato)
                    .addComponent(lblNumdeContrato1)
                    .addComponent(lblNumdeContrato2)
                    .addComponent(lblNumdeContrato3)
                    .addComponent(lblNumdeContrato4)
                    .addComponent(lblNumdeContrato5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlFlitrosDeBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNumeroContrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEspacio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFechaDesde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFechaHasta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlFlitrosDeBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscar)
                    .addComponent(btnLimpiar))
                .addContainerGap())
        );

        pnlResultados.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel4.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel4.setText("Resultados:");

        tblContratos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Número de contrato", "Cliente", "Espacio", "Fecha Inicio", "Fecha Fin", "Estado", "Costo Total"
            }
        ));
        scllResultados.setViewportView(tblContratos);

        javax.swing.GroupLayout pnlResultadosLayout = new javax.swing.GroupLayout(pnlResultados);
        pnlResultados.setLayout(pnlResultadosLayout);
        pnlResultadosLayout.setHorizontalGroup(
            pnlResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlResultadosLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(scllResultados, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        pnlResultadosLayout.setVerticalGroup(
            pnlResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlResultadosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scllResultados, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE))
        );

        btnAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Edit.png"))); // NOI18N
        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(this::btnAceptarActionPerformed);

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Cancel.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(this::btnCancelarActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBuscarContacto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlFlitrosDeBusqueda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlResultados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(btnCancelar)
                .addGap(43, 43, 43))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(pnlBuscarContacto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlFlitrosDeBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlResultados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAceptar)
                    .addComponent(btnCancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed

    String numero = txtNumeroContrato.getText().trim();
    String cliente = txtCedula.getText().trim();
    String espacio = txtEspacio.getText().trim();
    String estado = cmbEstado.getSelectedItem().toString();
    String fechaDesdeTexto = txtFechaDesde.getText().trim();
    String fechaHastaTexto = txtFechaHasta.getText().trim();

    LocalDate fechaDesde = controlador.convertirFecha(fechaDesdeTexto);
    LocalDate fechaHasta = controlador.convertirFecha(fechaHastaTexto);

    DefaultTableModel modelo =(DefaultTableModel) tblContratos.getModel();
    modelo.setRowCount(0);

    Iterator<Contrato> contratos =controlador.getContratos();

    if (contratos == null) {
        showError("No hay contratos registrados");
        return;
    }

    while (contratos.hasNext()) {

        Contrato contrato = contratos.next();

        boolean coincideNumero = numero.isEmpty()|| String.valueOf(contrato.getNumeroContrato()).contains(numero);
        boolean coincideCliente = cliente.isEmpty()|| contrato.getCliente().getCedula().contains(cliente);
        boolean coincideEspacio = espacio.isEmpty() || String.valueOf(contrato.getEspacio().getId_Espacio()).contains(espacio);
        boolean coincideEstado = estado.equals("Todos")|| contrato.getEstado().toString().equals(estado);
        boolean coincideFechaDesde =fechaDesde == null|| !contrato.getFechaInicio().isBefore(fechaDesde);
        boolean coincideFechaHasta =fechaHasta == null|| !contrato.getFechaFinal().isAfter(fechaHasta); 
        

        if (coincideNumero && coincideCliente && coincideEspacio && coincideFechaDesde && coincideFechaHasta && coincideEstado) {

            modelo.addRow(new Object[]{
                contrato.getNumeroContrato(),
                contrato.getCliente().getCedula(),
                contrato.getEspacio().getId_Espacio(),
                contrato.getFechaInicio(),
                contrato.getFechaFinal(),
                contrato.getEstado(),
                contrato.getTotal()
            });
        }
    }

    if (modelo.getRowCount() == 0) {
        showError("Contrato no encontrado");
    }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
       int fila = tblContratos.getSelectedRow();

    if (fila == -1) {
        showError("Debe seleccionar un contrato");
        return;
    }

    int numeroContrato = Integer.parseInt(tblContratos.getValueAt(fila, 0).toString());

    Contrato contrato =
            controlador.findContrato(numeroContrato);

    if (contrato != null) {
        vistaContrato.showData(contrato);
        controlador.setView(vistaContrato);
        dispose();
    }
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        controlador.setView(vistaContrato);
    dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed

    txtNumeroContrato.setText("");
    txtCedula.setText("");
    txtEspacio.setText("");
    txtFechaDesde.setText("");
    txtFechaHasta.setText("");

    cmbEstado.setSelectedIndex(0);

    cargarTabla();

    }//GEN-LAST:event_btnLimpiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VistaBuscarContrato().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JComboBox<String> cmbEstado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblNumdeContrato;
    private javax.swing.JLabel lblNumdeContrato1;
    private javax.swing.JLabel lblNumdeContrato2;
    private javax.swing.JLabel lblNumdeContrato3;
    private javax.swing.JLabel lblNumdeContrato4;
    private javax.swing.JLabel lblNumdeContrato5;
    private javax.swing.JPanel pnlBuscarContacto;
    private javax.swing.JPanel pnlFlitrosDeBusqueda;
    private javax.swing.JPanel pnlResultados;
    private javax.swing.JScrollPane scllResultados;
    private javax.swing.JTable tblContratos;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtEspacio;
    private javax.swing.JTextField txtFechaDesde;
    private javax.swing.JTextField txtFechaHasta;
    private javax.swing.JTextField txtNumeroContrato;
    // End of variables declaration//GEN-END:variables
}
